-- Hand-derived from entity source in a sandbox with no live Postgres/compiler to
-- verify against — cross-check against the real production schema
-- (`pg_dump --schema-only`) or a fresh `mvn spring-boot:run` boot before trusting
-- this for a new environment.
--
-- This file exists only so that Flyway has *a* V1 to register. On the existing
-- production database, `spring.flyway.baseline-on-migrate: true` +
-- `spring.flyway.baseline-version: 1` mean Flyway will record "schema is
-- already at V1" WITHOUT executing this DDL (baseline, not migrate) — so
-- pre-existing tables are never touched by this script. This script's DDL only
-- actually runs on a brand-new, empty database (e.g. a fresh dev/CI Postgres).
--
-- Table/column names below follow Spring Boot's default Hibernate physical
-- naming strategy (camelCase -> snake_case) except where an entity has an
-- explicit @Table(name=...) / @Column(name=...), which takes precedence.
-- IDENTITY-strategy primary keys are emitted as `GENERATED BY DEFAULT AS
-- IDENTITY`, the modern Postgres/Hibernate 6 default; this has not been
-- diffed against what an older Hibernate `ddl-auto: update` run may have
-- actually created (e.g. bigserial) — irrelevant for baseline-on-migrate on
-- the existing DB, but worth checking if you ever `pg_dump --schema-only` and
-- diff.

-- =====================================================================
-- users
-- =====================================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    approved_at TIMESTAMP,
    approved_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- =====================================================================
-- about_content (singleton row, id always 1, app-assigned — not IDENTITY)
-- =====================================================================
CREATE TABLE about_content (
    id BIGINT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- =====================================================================
-- access_groups
-- =====================================================================
CREATE TABLE access_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_access_groups_slug UNIQUE (slug)
);

-- =====================================================================
-- audit_logs (actor_user_id is a plain column, no FK — see AuditLog.java)
-- =====================================================================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100),
    metadata TEXT,
    created_at TIMESTAMP NOT NULL
);

-- =====================================================================
-- posts
-- =====================================================================
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    excerpt VARCHAR(1000),
    content TEXT NOT NULL,
    category VARCHAR(255),
    tags VARCHAR(1000),
    status VARCHAR(255) NOT NULL,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    private_metadata_visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC_METADATA',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    cover_image_data BYTEA,
    cover_image_content_type VARCHAR(100),
    cover_image_original_filename VARCHAR(255),
    cover_image_size BIGINT,
    view_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_posts_slug UNIQUE (slug)
);

-- =====================================================================
-- content_images (id is an app-assigned UUID string, not IDENTITY)
-- =====================================================================
CREATE TABLE content_images (
    id VARCHAR(255) PRIMARY KEY,
    data BYTEA NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255),
    size BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL
);

-- =====================================================================
-- content_videos (id is an app-assigned UUID string, not IDENTITY)
-- =====================================================================
CREATE TABLE content_videos (
    id VARCHAR(255) PRIMARY KEY,
    data BYTEA NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255),
    size BIGINT NOT NULL,
    duration_seconds INTEGER NOT NULL,
    uploaded_at TIMESTAMP NOT NULL
);

-- =====================================================================
-- post_attachments
-- =====================================================================
CREATE TABLE post_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    data BYTEA NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    attachment_type VARCHAR(20) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_attachments_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- =====================================================================
-- comments
-- =====================================================================
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT,
    author_name VARCHAR(100) NOT NULL,
    author_email VARCHAR(100),
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- =====================================================================
-- series
-- =====================================================================
CREATE TABLE series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_series_slug UNIQUE (slug)
);

-- =====================================================================
-- series_posts
-- =====================================================================
CREATE TABLE series_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_series_posts_series FOREIGN KEY (series_id) REFERENCES series (id),
    CONSTRAINT fk_series_posts_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT uk_series_posts_series_post UNIQUE (series_id, post_id),
    CONSTRAINT uk_series_posts_series_position UNIQUE (series_id, position)
);

-- =====================================================================
-- books
-- =====================================================================
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    description VARCHAR(4000),
    category VARCHAR(255),
    file_type VARCHAR(10) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    file_version INTEGER NOT NULL DEFAULT 1,
    cover_image_data BYTEA,
    cover_image_content_type VARCHAR(100),
    cover_image_size BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    metadata_visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC_METADATA',
    downloadable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    CONSTRAINT uk_books_slug UNIQUE (slug)
);

-- =====================================================================
-- book_files (one row per book, enforced by unique FK)
-- =====================================================================
CREATE TABLE book_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    data BYTEA NOT NULL,
    CONSTRAINT fk_book_files_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT uk_book_files_book UNIQUE (book_id)
);

-- =====================================================================
-- book_highlights
-- =====================================================================
CREATE TABLE book_highlights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    file_version INTEGER NOT NULL,
    anchor_type VARCHAR(16) NOT NULL,
    start_offset INTEGER,
    end_offset INTEGER,
    page_number INTEGER,
    rects TEXT,
    color VARCHAR(10) NOT NULL,
    text VARCHAR(2000) NOT NULL,
    note VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_book_highlights_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_highlights_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_book_highlights_book_user ON book_highlights (book_id, user_id);
CREATE INDEX idx_book_highlights_user_updated ON book_highlights (user_id, updated_at);

-- =====================================================================
-- book_reading_progress
-- =====================================================================
CREATE TABLE book_reading_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    total INTEGER NOT NULL,
    unit VARCHAR(10) NOT NULL,
    percent INTEGER NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_book_reading_progress_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_reading_progress_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_book_reading_progress_book_user UNIQUE (book_id, user_id)
);

-- =====================================================================
-- exams
-- =====================================================================
CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    time_limit INTEGER,
    score_scale INTEGER,
    pass_score DOUBLE PRECISION,
    status VARCHAR(255) NOT NULL,
    visibility VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- =====================================================================
-- questions
-- =====================================================================
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    order_index INTEGER NOT NULL,
    points INTEGER NOT NULL,
    question_type VARCHAR(255) NOT NULL,
    correct_text_answer TEXT,
    CONSTRAINT fk_questions_exam FOREIGN KEY (exam_id) REFERENCES exams (id)
);

-- =====================================================================
-- question_options
-- =====================================================================
CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    order_index INTEGER NOT NULL,
    CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES questions (id)
);

-- =====================================================================
-- exam_attempts
-- =====================================================================
CREATE TABLE exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    score INTEGER,
    total_points INTEGER,
    started_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_exam_attempts_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_attempts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- =====================================================================
-- exam_answers
-- =====================================================================
CREATE TABLE exam_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    text_answer TEXT,
    correct BOOLEAN,
    CONSTRAINT fk_exam_answers_attempt FOREIGN KEY (attempt_id) REFERENCES exam_attempts (id),
    CONSTRAINT fk_exam_answers_question FOREIGN KEY (question_id) REFERENCES questions (id)
);

-- =====================================================================
-- exam_answer_selected_options (@ManyToMany join table, ExamAnswer.selectedOptions)
-- =====================================================================
CREATE TABLE exam_answer_selected_options (
    exam_answer_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    PRIMARY KEY (exam_answer_id, option_id),
    CONSTRAINT fk_exam_answer_selected_options_answer FOREIGN KEY (exam_answer_id) REFERENCES exam_answers (id),
    CONSTRAINT fk_exam_answer_selected_options_option FOREIGN KEY (option_id) REFERENCES question_options (id)
);

-- =====================================================================
-- access_requests
-- =====================================================================
CREATE TABLE access_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    message VARCHAR(1000),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    reviewed_by BIGINT,
    CONSTRAINT fk_access_requests_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_access_requests_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- =====================================================================
-- book_access_groups
-- =====================================================================
CREATE TABLE book_access_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    access_group_id BIGINT NOT NULL,
    CONSTRAINT fk_book_access_groups_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_access_groups_group FOREIGN KEY (access_group_id) REFERENCES access_groups (id),
    CONSTRAINT uk_book_access_groups_book_group UNIQUE (book_id, access_group_id)
);

-- =====================================================================
-- book_user_permissions
-- =====================================================================
CREATE TABLE book_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    granted_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_book_user_permissions_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_user_permissions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_book_user_permissions_book_user UNIQUE (book_id, user_id)
);

-- =====================================================================
-- exam_access_groups
-- =====================================================================
CREATE TABLE exam_access_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    access_group_id BIGINT NOT NULL,
    CONSTRAINT fk_exam_access_groups_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_access_groups_group FOREIGN KEY (access_group_id) REFERENCES access_groups (id),
    CONSTRAINT uk_exam_access_groups_exam_group UNIQUE (exam_id, access_group_id)
);

-- =====================================================================
-- exam_user_permissions
-- =====================================================================
CREATE TABLE exam_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    granted_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_exam_user_permissions_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_user_permissions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_exam_user_permissions_exam_user UNIQUE (exam_id, user_id)
);

-- =====================================================================
-- post_access_groups
-- =====================================================================
CREATE TABLE post_access_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    access_group_id BIGINT NOT NULL,
    CONSTRAINT fk_post_access_groups_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_access_groups_group FOREIGN KEY (access_group_id) REFERENCES access_groups (id),
    CONSTRAINT uk_post_access_groups_post_group UNIQUE (post_id, access_group_id)
);

-- =====================================================================
-- post_user_permissions
-- =====================================================================
CREATE TABLE post_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    granted_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_user_permissions_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_user_permissions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_post_user_permissions_post_user UNIQUE (post_id, user_id)
);

-- =====================================================================
-- user_access_groups
-- =====================================================================
CREATE TABLE user_access_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_group_id BIGINT NOT NULL,
    granted_at TIMESTAMP NOT NULL,
    granted_by BIGINT,
    CONSTRAINT fk_user_access_groups_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_access_groups_group FOREIGN KEY (access_group_id) REFERENCES access_groups (id),
    CONSTRAINT uk_user_access_groups_user_group UNIQUE (user_id, access_group_id)
);
