-- First real schema drift caught by ddl-auto: validate, on the actual dev
-- Postgres database, right after V1 was introduced: `book_highlights` was
-- missing entirely. Root cause was operational, not a V1 authoring mistake —
-- the backend hadn't been successfully restarted with the code that added
-- this entity since it landed, so ddl-auto: update (the old schema-management
-- mode) never got a chance to create it. validate mode caught this
-- immediately and loudly on boot instead of silently drifting further.
--
-- V1 is already baselined on this database (baseline-on-migrate marks it
-- "applied" without executing it) — so the fix is a new versioned migration,
-- not an edit to V1. DDL below matches V1__baseline.sql's book_highlights
-- definition exactly.
CREATE TABLE book_highlights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    file_version INTEGER NOT NULL,
    anchor_type VARCHAR(16) NOT NULL,
    start_offset INTEGER,
    end_offset INTEGER,
    page_number INTEGER,
    rects TEXT,
    color VARCHAR(10) NOT NULL,
    text VARCHAR(2000) NOT NULL,
    note VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_book_highlights_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_highlights_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_book_highlights_book_user ON book_highlights (book_id, user_id);
CREATE INDEX idx_book_highlights_user_updated ON book_highlights (user_id, updated_at);
