-- Tools module — self-contained HTML/CSS/JS artifacts (calculators,
-- diagrams, checklists), admin-authored, served as their own page. See
-- docs/03-architecture.md §3.1/§4.6 and docs/04-api-contract.md §11.
--
-- html_source lives in its own table (tool_sources), not a column on
-- tools, for the same reason book_files is split from books (§4.3): a bulk
-- listing query must never risk loading a ~1 MB blob per row.

CREATE TABLE tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    tags VARCHAR(1000),
    excerpt VARCHAR(1000),
    cover_image_data BYTEA,
    cover_image_content_type VARCHAR(100),
    cover_image_original_filename VARCHAR(255),
    cover_image_size BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    created_by BIGINT,
    CONSTRAINT uk_tools_slug UNIQUE (slug),
    CONSTRAINT fk_tools_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

-- tool_sources (one row per tool, enforced by unique FK) — mirrors book_files.
CREATE TABLE tool_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id BIGINT NOT NULL,
    html_source TEXT NOT NULL,
    CONSTRAINT fk_tool_sources_tool FOREIGN KEY (tool_id) REFERENCES tools (id),
    CONSTRAINT uk_tool_sources_tool UNIQUE (tool_id)
);
