package com.example.blog.audit;

/** Fixed vocabulary of auditable actions — keeps `AuditLog.action` values consistent. */
public enum AuditAction {
    USER_APPROVED,
    USER_REJECTED,
    USER_SUSPENDED,
    USER_REACTIVATED,
    USER_ADDED_TO_GROUP,
    USER_REMOVED_FROM_GROUP,
    POST_MARKED_PRIVATE,
    POST_MARKED_PUBLIC,
    POST_PERMISSION_GRANTED,
    POST_PERMISSION_REVOKED,
    EXAM_PERMISSION_GRANTED,
    EXAM_PERMISSION_REVOKED,
    BOOK_PERMISSION_GRANTED,
    BOOK_PERMISSION_REVOKED,
    ACCESS_GROUP_CREATED,
    ACCESS_GROUP_UPDATED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_REJECTED
}
